name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_opencv:
    uses: ./.github/workflows/build_opencv.yml

  build:
    needs: build_opencv

    runs-on: macos-latest
    
    strategy:
      matrix:
        # python-version: ["3.10", "3.11", "3.12"]
        python-version: ["3.12"]
        
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 3.24.4
        
    - name: config env
      shell: bash
      run: |
        pip3 install setuptools
        pip3 install --user six

    - uses: actions/checkout@v4

    - name: Download file for "build opencv"
      uses: actions/download-artifact@v4
      with:
        name: release

    - name: replace core and imgproc
      shell: bash
      run: |
        ls -lh
        cp release/lib/Release/libopencv_imgproc.a mediapipe/tasks/c/vision/
        cp release/lib/Release/libopencv_core.a mediapipe/tasks/c/vision/

    - name: build
      shell: bash
      run: |
        uname -m
        bazel build --verbose_failures -c opt --config ios_arm64 --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/tasks/c/vision/hand_landmarker:libhand_landmarker.dylib
