name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # workflow_dispatch:
  #  inputs:
  #     version: 
  #       description: '版本号'
  #       required: false

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        # python-version: ["3.10", "3.11", "3.12"]
        python-version: ["3.12"]
        
    # strategy:
    #   matrix:
    #     # You can add more, for any target you'd like!
    #     include:
    #       - name: macos-latest
    #         os: macos-latest
            

    steps:
    - uses: actions/checkout@v4

    # - name: build
    #   shell: bash
    #   run: |
    #     uname -m

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    # - name: config env
    #   shell: bash
    #   run: |
    #     brew install xyz
        
    - name: Install CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 3.24.4
        
        
    - name: config env
      shell: bash
      run: |
        pip install setuptools
        
    #- name: setup_opencv
    #  shell: bash
    #  run: |
    #    chmod +x ./setup_opencv.sh
    #    ./setup_opencv.sh

    - name: build
      shell: bash
      run: |
        uname -m
        # export HERMETIC_PYTHON_VERSION=3.12
        bazel build --verbose_failures -c opt --config ios_arm64 --define OPENCV=source --strip always --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/tasks/c/vision/hand_landmarker:libhand_landmarker.dylib

    # - name: build
    #   shell: bash
    #   run: |
    #     uname -m
    # #    bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 //mediapipe/tasks/c/vision/object_detector:object_detection_tflite_speed_test
    # # chmod +x ./build_desktop_examples.sh
    # # ./build_desktop_examples.sh

    # - name: check binary
    #   shell: bash
    #   run: |
    #     file bazel-bin/mediapipe/tasks/c/vision/object_detector/object_detection_tflite_speed_test

    # - name: Upload archive
    #   uses: actions/upload-artifact@v4.5.0
    #   with:
    #     name: object_detection_tflite_speed_test
    #     path: bazel-bin/mediapipe/tasks/c/vision/object_detector/object_detection_tflite_speed_test
